version: "3.8"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    env_file:
      - ./.env
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
